traiterJson({
"trait":2,
"scoreJ":23,
"scoreJ5":0,
"scoreR":24,
"scoreR5":0,
"cols":[
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2}
]
});
